### PR TITLE
Styling of latest back end as of 02.25

### PR DESCRIPTION
**Pull request by aistutja**
Changes to style.css, header.jsp, index.jsp. Minor changes on headerResult.jsp, result.jsp, article.jsp. Light gray header.

### CODE REVIEW

**Comment by Justinasin** [comment]
Seems code is fine

**Review by Justinasin — COMMENTED** [review]
Accepting

**Review by Justinasin — APPROVED** [review]

**Review by Justinasin — DISMISSED** [review]
Aiste please pull again from master and initiate pull request again

**Review by Raimondas-Alisauskas — APPROVED** [review]

**Review by VladislavSinkevich — APPROVED** [review]

**Review by aistutja — COMMENTED** [review]
ok

**Pull request merged**
