### PR TITLE
Justas markauskas

### PR DESCRIPTION
**Pull request by JustasMarkauskas**
Created index.html and index.jsp

### CODE REVIEW

**Review by Artiom171 — DISMISSED** [review]

**Comment by Justinasin** [comment]
Format the code, don't leave any extra spaces

**Comment by Justinasin** [comment]
Delete index.html

**Review by Justinasin — CHANGES_REQUESTED** [review]
Change jsp files according to example with all the names and labels of all the fields.

**Review by Justinasin — APPROVED** [review]
Seems good for now. Later we gonna change field and button names as it shouls be according to Back-end

**Review by Artiom171 — APPROVED** [review]

**Pull request merged**
